### ISSUE TITLE
Convert to Py3 only support and drop Py2.7 support

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ufolint#19]
Associated issues to make conversion:

- #17

**Comment by madig** [comment]
I recommend going 3.6+ only for those delicios f-strings and being able to use `Path`s in `open()` :)

**Comment by chrissimpkins** [comment]
@felipesanches @graphicore any issues with a move to Py3 only support here in the Font Bakery project?  Looking at the setup.py it appears that you are enforcing Py3.6+ now?

@graphicore you raised the issue of the Py3 change in Font Bakery due to incompatibilities in the dashboard.  Are you running ufolint in the dashboard and would a switch to Py3 only support here affect you in FB Dashboard?

**Comment by felipesanches** [comment]
My understanding and expectations are that there's no going back to python 2 on Font Bakery anymore :-)

**Comment by chrissimpkins** [comment]
@felipesanches ty for the feedback!

**Comment by chrissimpkins** [comment]
@graphicore excellent, thanks! (and congratulations!!)

**Comment by chrissimpkins** [comment]
Py 2.7 and Py < 3.6 support was dropped as of the v0.4.0 release.  There is a new `py27` branch for those who need access to the source as of the last `py27` support release.
