### ISSUE TITLE
Convert to fontTools.ufoLib?

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/ufolint#20]
The unified-font-object/ufoLib (PyPI `ufoLib`) repository is being converted to bug fix patch only and future work on the ufoLib library is going to take place in fontTools.ufoLib.   We currently use unified-font-object/ufoLib as the UFO reader project dependency here.  The intent is to catch all read validations that raise UFOLibError's and publish a human readable message to the user about the problem that was encountered as well as confirm that a non-zero exit status code is raised for CI testing purposes.

Should we convert to fontTools.ufoLib where development will continue?  Probably so.

~~Need to research the UFOReader validation methods with the fork to confirm that there were not significant changes in what validations are occurring.~~ See https://github.com/source-foundry/ufolint/issues/20#issuecomment-431889243

**Comment by anthrotype** [comment]
There were no changes so far

**Comment by chrissimpkins** [comment]
From Cosimo in https://github.com/source-foundry/ufolint/pull/18#issuecomment-431885423

fontTools.ufoLib is meant to be (at least initially) a drop-in replacement for ufoLib, so it should be as easy as requiring `fonttools[ufo] >= 3.31.0` (https://github.com/typesupply/defcon/pull/204/commits/bbbd118ff58b3f2fdb307b7df43ab64f3c00415e) and modifying the imports (https://github.com/typesupply/defcon/pull/204/commits/e9181ed38654da056fb0c6c45dd73ca88a67dd41)

**Comment by chrissimpkins** [comment]
Open for comment.  If this change will impact you and is not desirable, please weigh in.

**Comment by anthrotype** [comment]
hm me? not really..
but what *change*? there were none.. :grin:

**Comment by chrissimpkins** [comment]
> hm me?
nope :)  Anyone out there who is using the tool

> but what change? there were none..
Not in ufoLib, in ufolint.  This will change the dependency away from ufoLib and to fontTools.ufoLib.  Due diligence to make sure that we are not causing unnecessary pain that I am not aware of.

**Comment by anthrotype** [comment]
oh sorry :blush: 

well, fonttools itself was already a dependency of ufoLib.
The new fontTools.ufoLib requires the `fs` module (aka pyfilesystem2), because it adds support for reading / writing UFOZ (zipped ufo)

**Comment by madig** [comment]
Hm. The only pain I'd have is that I need to update fonttools in the CI job for linting purposes. All our project builds are venv'd with a fixed requirements.txt, which sometimes has things like `ufoLib==2.1.1` in it -- that's what lead me to send that PR. Since linting is supposed to be a step before any compiling is done in the next CI job, stuff should just be downgraded again like nothing's happend. So, yeah, I'm in favor.

**Comment by chrissimpkins** [comment]
Do you need time to make any changes on your end? There is absolutely no rush to make the transition.  The fork just took place.

**Comment by madig** [comment]
The change needed was `pip install -U "ufolib>=2.2.0"`, so I'm fine I think 😁 There is always a rush to do everything at the same time! So much to do, so little time 😬

**Comment by madig** [comment]
Don't think so 🤔

**Comment by chrissimpkins** [comment]
Haha! OK.

**Comment by chrissimpkins** [comment]
done as of v0.4.0 release
