### ISSUE TITLE
Scope of UFOLint?

### ISSUE THREAD

**Issue by madig** [source-foundry/ufolint#7]
Hi!
I'm wondering if it would be within the scope of the project to check the semantics of UFO fields. E.g.:

- Presence of openTypeNameVersion, UniqueID fields which are automatically generated by ufo2ft
- versionMajor/Minor disagree with what's in openTypeNameVersion
- Some glyph roundtripped from a .glyphs has a metrics key but the numeric side-bearing doesn't match up

Maybe even something as simple as importing a local module that runs all the checks one wants.

**Comment by chrissimpkins** [comment]
Would love to support all of these Nikolaus.  Everything that you mentioned is within the scope of the project.  Do you feel that any of these tests would be more appropriate in ufoLib and exposed as public functions/methods for use here? It would be worth answering that question before we dig in and generate a good deal of testing / verification code outside of the library.   

To support these things myself, I need some detailed feedback about proper/desired checks and a set of expected values / parameters.  Once in place I am able to get going on this and highly encourage / welcome source commits from anyone else with an interest.  Are any of these tests something that you would like to contribute?   I am more than willing to add repo write access if you would like to collaborate on this.  I reached the limit of my needs for our project and this is the only reason that development has stalled.  

Once discussion is complete here (and we decide to push ahead), let's close and open each issue as a new thread for work.

**Comment by madig** [comment]
I think the fields I mentioned should be checked in UFOLint, as they are all legal in themselves to ufoLib I suppose. I actually need to collect more things first before proposing concrete checks.

This inquiry is actually part of my Dalton Maag assignment to get more checking tools up and running :) Fontbakery can detect a lot, but can't see that a superfluous unique ID field is present in the sources :)

**Comment by chrissimpkins** [comment]
Happy to help here with things that are generally useful out there.  Would recommend that we steer away from company specific / project specific checks.  If there is a common use case for testing any of these needs out there we can make it happen.

**Comment by chrissimpkins** [comment]
And so that it is stated, the original purpose was to lint UFO for validity in the setting of collaborative design projects.  I didn't want to manually 'proof' ufo files for capacity to compile across various contributors and their chosen editors.  This serves as a stop for invalid source commits in PR for us.

**Comment by chrissimpkins** [comment]
I think that suggestions are appropriate as long as we can maintain that goal of serving as a 'linter' for capacity to compile and valid design source (extends the original intent here) it can be justified.

**Comment by graphicore** [comment]
> This inquiry is actually part of my Dalton Maag assignment to get more checking tools up and running :) Fontbakery can detect a lot, but can't see that a superfluous unique ID field is present in the sources :)

Though, the kinds of checks you suggest here seem to me like a good fit for a special Font Bakery based UFO "specification" (= a collection of tests.).
At the moment, Font Bakery does only `TTF` checks (in the `googlefonts.py` specification), but it's technically possible (and intended) to run any kind of checks really.
I would rather suggest to make a UFO-specification for Font Bakery, using UFOLint and adding further UFO-sanity-checks to that. Font Bakery really just provides the runner and reporter infrastructure, as well as the web-based "Font Bakery Dashboard" which could also check and report with other specifications. The idea is to share the tooling effort as much as the checks that are useful for everyone. I'd be glad to help.

**Comment by chrissimpkins** [comment]
@graphicore thanks Lasse.

@madig Feel free to open new issues here if you feel that any of these are appropriate in this project following Lasse's suggestion in https://github.com/source-foundry/ufolint/issues/7#issuecomment-373154323.   We could consider a library of public functions/methods for testing that could be exposed to other projects including Font Bakery where the tests can be combined into test suites that a given project needs.  If Lasse and crew are willing to accept all of the implementation source in Font Bakery, it may be a better option there as they have a mature testing / logging structure in place.  Let me know if there is anything that I can do.  Happy to help and remain willing to support these tests here if helpful.

**Comment by madig** [comment]
Alright, will have a look at integrating things into Fontbakery then and discuss possible checks for ufolint :)

**Comment by chrissimpkins** [comment]
@madig sounds good.  Let me know if there is anything that I can do.
