### ISSUE TITLE
Parallel runs

### ISSUE THREAD

**Issue by madig** [source-foundry/ufolint#72]
I'm looking at a project with ten large masters and running ufolint serially is slow. I could use `xargs -P ...` to run it in parallel, but then output is jumbled. Maybe the tool itself could become parallel or can have a switch to produce a log file? Needs more thinking.

**Comment by chrissimpkins** [comment]
This is a very good idea Niko.  It would take a significant refactor to make it happen.  This project likely requires that refactor in any case.  Thoughts about use of this as a standalone tool vs. pushing these checks somewhere like fontbakery?  I don't know if it landed in master yet but I know that Lasse was working on a parallel workflow for FB checks.  At the moment, I think that FB may be executing ufolint for the checks here?

**Comment by madig** [comment]
I have since found that using `parallel` gets the problem done, at least on Linux.

I was asking myelf the same question back in the day when I was working on fontbakery and now appreciate ufolint being a separate tool with few dependencies.

**Comment by chrissimpkins** [comment]
Rust rewrite? :)

**Comment by madig** [comment]
Yes. All we need to do is implement all sanity checks in norad. I
implemented quite a few but am missing for example id uniqueness checking
and other things.

**Comment by chrissimpkins** [comment]
Taking a look at Norad now.  Where is the proper spot to add validations in the project?  It looks like they maybe live in `ufo.rs`?

**Comment by madig** [comment]
So... partly you parse, not validate (see how the fontinfo WOFF stuff is tied to a rigid structure through the type system, the simplest case being the LTR/RTL markers for WOFF attributes), partly you do actually validate (see the validator fn in the same file). It's complicated. One could keep a central memo of seen IDs while reading the UFO and check with it upon encountering IDs anywhere. It's best to follow the code flow first and see where you can hook in.

**Comment by chrissimpkins** [comment]
Is a strict spec validation set on reads within the scope of that project?  Or better to use it for R/W and build an executable based on the library?

**Comment by madig** [comment]
Hm!!!! I don't know but it would be a shame to have Norad be laissez-faire. Bad data is bad data even when you are 1-2 orders of magnitudes faster at processing it.

**Comment by chrissimpkins** [comment]
SG!  Let me familiarize myself with the code base and I'll see if/how I might contribute.
